version: '3.9'

services:
  webserver:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on: app
  app:
    build: .
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    depends_on:
      - 'postgres'
      - 'redis'
    command: ['node', 'dist/index.js']
    restart: always
  postgres:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-h postgres',
          '-d ${POSTGRES_USER:-postgres}',
          '-U ${POSTGRES_USER:-postgres}',
        ]
      timeout: 5s
      interval: 30s
      start_period: 30s
      retries: 3
  redis:
    image: 'redis'

volumes:
  postgres:
