import AuthProvider from '@karnival/auth-provider';
import AppBar from '@karnival/components/app-bar';
import { Provider as ChakraProvider } from '@karnival/components/chakra-ui/provider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ChakraProvider>
            <AppBar />
            {children}
          </ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
